In [36]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso, LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import GridSearchCV

import pickle

In [37]:
url="data/Sleep_health_and_lifestyle_dataset.csv"
data=pd.read_csv(url,encoding='latin-1')
data.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [38]:
data.shape

(374, 13)

In [39]:
data.isnull().sum()

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    object
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    object
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    object
 9   Blood Pressure           374 non-null    object
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           155 non-null    object
dtypes: float64(1), int64(7), object(5)
memory usage: 38.1+ KB

In [41]:
data["Sleep Disorder"].value_counts()

Sleep Disorder
Sleep Apnea    78
Insomnia       77
Name: count, dtype: int64

In [42]:
data.columns = data.columns.str.replace(' ', '_')

In [43]:
data.head()

,Person_ID,Gender,Age,Occupation,Sleep_Duration,Quality_of_Sleep,Physical_Activity_Level,Stress_Level,BMI_Category,Blood_Pressure,Heart_Rate,Daily_Steps,Sleep_Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [44]:
data.columns

Index(['Person_ID', 'Gender', 'Age', 'Occupation', 'Sleep_Duration',
       'Quality_of_Sleep', 'Physical_Activity_Level', 'Stress_Level',
       'BMI_Category', 'Blood_Pressure', 'Heart_Rate', 'Daily_Steps',
       'Sleep_Disorder'],
      dtype='object')

In [45]:
numeric_data = data.select_dtypes(include=['number'])
numeric_data.corr()['Sleep_Duration']

Person_ID                  0.296305
Age                        0.344709
Sleep_Duration             1.000000
Quality_of_Sleep           0.883213
Physical_Activity_Level    0.212360
Stress_Level              -0.811023
Heart_Rate                -0.516455
Daily_Steps               -0.039533
Name: Sleep_Duration, dtype: float64

In [46]:
data.head()

,Person_ID,Gender,Age,Occupation,Sleep_Duration,Quality_of_Sleep,Physical_Activity_Level,Stress_Level,BMI_Category,Blood_Pressure,Heart_Rate,Daily_Steps,Sleep_Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [47]:
data=data.drop(columns=['Person_ID', 'Sleep_Disorder'])

In [48]:
data.head()

,Gender,Age,Occupation,Sleep_Duration,Quality_of_Sleep,Physical_Activity_Level,Stress_Level,BMI_Category,Blood_Pressure,Heart_Rate,Daily_Steps
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200
1,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000
3,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000

In [49]:
data = pd.get_dummies(data, columns=['Gender'], drop_first=False)

In [50]:
data.head()

,Age,Occupation,Sleep_Duration,Quality_of_Sleep,Physical_Activity_Level,Stress_Level,BMI_Category,Blood_Pressure,Heart_Rate,Daily_Steps,Gender_Female,Gender_Male
0,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,False,True
1,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,False,True
2,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,False,True
3,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,False,True
4,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,False,True

In [51]:
data['Gender_Female'] = data['Gender_Female'].astype(int)
data['Gender_Male'] = data['Gender_Male'].astype(int)

In [52]:
data.head()

,Age,Occupation,Sleep_Duration,Quality_of_Sleep,Physical_Activity_Level,Stress_Level,BMI_Category,Blood_Pressure,Heart_Rate,Daily_Steps,Gender_Female,Gender_Male
0,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,0,1
1,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,0,1
2,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,0,1
3,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,0,1
4,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,0,1

In [53]:
# Ensure no leading/trailing spaces in the BMI_Category column
data['BMI_Category'] = data['BMI_Category'].str.strip()

# Apply one-hot encoding
bmi_encoded = pd.get_dummies(data['BMI_Category'], prefix='BMI')

# Concatenate the encoded columns back to the dataset
data = pd.concat([data, bmi_encoded], axis=1)

# Drop the original 'BMI_Category' column
data.drop('BMI_Category', axis=1, inplace=True)

In [54]:
data.head()

,Age,Occupation,Sleep_Duration,Quality_of_Sleep,Physical_Activity_Level,Stress_Level,Blood_Pressure,Heart_Rate,Daily_Steps,Gender_Female,Gender_Male,BMI_Normal,BMI_Normal Weight,BMI_Obese,BMI_Overweight
0,27,Software Engineer,6.1,6,42,6,126/83,77,4200,0,1,False,False,False,True
1,28,Doctor,6.2,6,60,8,125/80,75,10000,0,1,True,False,False,False
2,28,Doctor,6.2,6,60,8,125/80,75,10000,0,1,True,False,False,False
3,28,Sales Representative,5.9,4,30,8,140/90,85,3000,0,1,False,False,True,False
4,28,Sales Representative,5.9,4,30,8,140/90,85,3000,0,1,False,False,True,False

In [55]:
bmi_columns = ['BMI_Normal','BMI_Normal Weight', 'BMI_Obese', 'BMI_Overweight']
for col in bmi_columns:
    data[col] = data[col].astype(int)

In [56]:
data.head()

,Age,Occupation,Sleep_Duration,Quality_of_Sleep,Physical_Activity_Level,Stress_Level,Blood_Pressure,Heart_Rate,Daily_Steps,Gender_Female,Gender_Male,BMI_Normal,BMI_Normal Weight,BMI_Obese,BMI_Overweight
0,27,Software Engineer,6.1,6,42,6,126/83,77,4200,0,1,0,0,0,1
1,28,Doctor,6.2,6,60,8,125/80,75,10000,0,1,1,0,0,0
2,28,Doctor,6.2,6,60,8,125/80,75,10000,0,1,1,0,0,0
3,28,Sales Representative,5.9,4,30,8,140/90,85,3000,0,1,0,0,1,0
4,28,Sales Representative,5.9,4,30,8,140/90,85,3000,0,1,0,0,1,0

In [57]:
data.rename(columns=lambda x: x.replace(" ", "_"), inplace=True)

In [58]:
data.head()

,Age,Occupation,Sleep_Duration,Quality_of_Sleep,Physical_Activity_Level,Stress_Level,Blood_Pressure,Heart_Rate,Daily_Steps,Gender_Female,Gender_Male,BMI_Normal,BMI_Normal_Weight,BMI_Obese,BMI_Overweight
0,27,Software Engineer,6.1,6,42,6,126/83,77,4200,0,1,0,0,0,1
1,28,Doctor,6.2,6,60,8,125/80,75,10000,0,1,1,0,0,0
2,28,Doctor,6.2,6,60,8,125/80,75,10000,0,1,1,0,0,0
3,28,Sales Representative,5.9,4,30,8,140/90,85,3000,0,1,0,0,1,0
4,28,Sales Representative,5.9,4,30,8,140/90,85,3000,0,1,0,0,1,0

In [59]:
data=data.drop(columns=['Occupation'])

In [60]:
data.head()

,Age,Sleep_Duration,Quality_of_Sleep,Physical_Activity_Level,Stress_Level,Blood_Pressure,Heart_Rate,Daily_Steps,Gender_Female,Gender_Male,BMI_Normal,BMI_Normal_Weight,BMI_Obese,BMI_Overweight
0,27,6.1,6,42,6,126/83,77,4200,0,1,0,0,0,1
1,28,6.2,6,60,8,125/80,75,10000,0,1,1,0,0,0
2,28,6.2,6,60,8,125/80,75,10000,0,1,1,0,0,0
3,28,5.9,4,30,8,140/90,85,3000,0,1,0,0,1,0
4,28,5.9,4,30,8,140/90,85,3000,0,1,0,0,1,0

In [61]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      374 non-null    int64
 1   Sleep_Duration           374 non-null    float64
 2   Quality_of_Sleep         374 non-null    int64
 3   Physical_Activity_Level  374 non-null    int64
 4   Stress_Level             374 non-null    int64
 5   Blood_Pressure           374 non-null    object
 6   Heart_Rate               374 non-null    int64
 7   Daily_Steps              374 non-null    int64
 8   Gender_Female            374 non-null    int64
 9   Gender_Male              374 non-null    int64
 10  BMI_Normal               374 non-null    int64
 11  BMI_Normal_Weight        374 non-null    int64
 12  BMI_Obese                374 non-null    int64
 13  BMI_Overweight           374 non-null    int64
dtypes: float64(1), int64(12), object(1)
memory usage: 41.0+ KB

In [62]:
data[['Systolic_BP', 'Diastolic_BP']] = data['Blood_Pressure'].str.split('/', expand=True)

# Convert the new columns to integers
data['Systolic_BP'] = data['Systolic_BP'].astype(int)
data['Diastolic_BP'] = data['Diastolic_BP'].astype(int)

# Drop the original 'Blood_Pressure' column (optional)
data.drop('Blood_Pressure', axis=1, inplace=True)

In [63]:
data.head()

,Age,Sleep_Duration,Quality_of_Sleep,Physical_Activity_Level,Stress_Level,Heart_Rate,Daily_Steps,Gender_Female,Gender_Male,BMI_Normal,BMI_Normal_Weight,BMI_Obese,BMI_Overweight,Systolic_BP,Diastolic_BP
0,27,6.1,6,42,6,77,4200,0,1,0,0,0,1,126,83
1,28,6.2,6,60,8,75,10000,0,1,1,0,0,0,125,80
2,28,6.2,6,60,8,75,10000,0,1,1,0,0,0,125,80
3,28,5.9,4,30,8,85,3000,0,1,0,0,1,0,140,90
4,28,5.9,4,30,8,85,3000,0,1,0,0,1,0,140,90

In [64]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      374 non-null    int64
 1   Sleep_Duration           374 non-null    float64
 2   Quality_of_Sleep         374 non-null    int64
 3   Physical_Activity_Level  374 non-null    int64
 4   Stress_Level             374 non-null    int64
 5   Heart_Rate               374 non-null    int64
 6   Daily_Steps              374 non-null    int64
 7   Gender_Female            374 non-null    int64
 8   Gender_Male              374 non-null    int64
 9   BMI_Normal               374 non-null    int64
 10  BMI_Normal_Weight        374 non-null    int64
 11  BMI_Obese                374 non-null    int64
 12  BMI_Overweight           374 non-null    int64
 13  Systolic_BP              374 non-null    int64
 14  Diastolic_BP             374 non-null    int64
dtypes: float64(1), int64(14)
memory usage: 44.0 KB

In [65]:
numeric_data = data.select_dtypes(include=['number'])
numeric_data.corr()['Sleep_Duration']

Age                        0.344709
Sleep_Duration             1.000000
Quality_of_Sleep           0.883213
Physical_Activity_Level    0.212360
Stress_Level              -0.811023
Heart_Rate                -0.516455
Daily_Steps               -0.039533
Gender_Female              0.121579
Gender_Male               -0.121579
BMI_Normal                 0.343835
BMI_Normal_Weight          0.061774
BMI_Obese                 -0.035896
BMI_Overweight            -0.368484
Systolic_BP               -0.180406
Diastolic_BP              -0.166570
Name: Sleep_Duration, dtype: float64

In [66]:
data.shape

(374, 15)

In [67]:
X=data.drop('Sleep_Duration',axis=1)
y=data['Sleep_Duration']

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [69]:
X_train.shape,X_test.shape

((280, 14), (94, 14))

In [70]:
def model_acc(model):
    model.fit(X_train,y_train)
    acc=model.score(X_test,y_test)
    print(str(model)+ '-->' + str(acc))

In [71]:
lr=LinearRegression()
model_acc(lr)

lasso=Lasso()
model_acc(lasso)

dt = DecisionTreeRegressor()
model_acc(dt)

rf = RandomForestRegressor()
model_acc(rf)

LinearRegression()-->0.8646304618583108
Lasso()-->0.4212448766813297
DecisionTreeRegressor()-->0.9554806147447942

RandomForestRegressor()-->0.9787536808385555

In [72]:

parameters = {'n_estimators':[10, 50, 100],
              'criterion':['squared_error','absolute_error','poisson']}

grid_obj = GridSearchCV(estimator=rf, param_grid=parameters)

grid_fit = grid_obj.fit(X_train, y_train)

best_model = grid_fit.best_estimator_
best_model

RandomForestRegressor(criterion='poisson')

In [73]:
best_model.score(X_test, y_test)

0.9781660920267677

In [ ]:
with open('predictor.pickle', 'wb') as file:
    pickle.dump(best_model, file)

In [75]:
X_train.columns

Index(['Age', 'Quality_of_Sleep', 'Physical_Activity_Level', 'Stress_Level',
       'Heart_Rate', 'Daily_Steps', 'Gender_Female', 'Gender_Male',
       'BMI_Normal', 'BMI_Normal_Weight', 'BMI_Obese', 'BMI_Overweight',
       'Systolic_BP', 'Diastolic_BP'],
      dtype='object')

In [76]:
pred_value = best_model.predict([[22, 6, 42, 8, 77, 4200, 1, 0, 1, 0, 0, 0, 126, 83]])
pred_value

c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([6.15758333])